// app-spa/src/lib/StockRow.svelte
<script lang="ts">
  import type { StockState } from '../types.js';

  export let stock: StockState;

  $: dir = stock.change >= 0 ? 'up' : 'down';
  $: priceFormatted  = stock.price.toFixed(2);
  $: changeFormatted = (stock.change >= 0 ? '+' : '') + (stock.change * 100).toFixed(2) + '%';
  $: volumeFormatted = stock.volume.toLocaleString('en-US');
</script>

<tr id="row-{stock.symbol}" class={dir === 'up' ? 'flash-up' : 'flash-down'}>
  <td class="symbol">{stock.symbol}</td>
  <td class="price {dir}">{priceFormatted}</td>
  <td class="change {dir}">{changeFormatted}</td>
  <td class="volume">{volumeFormatted}</td>
</tr>

// app-spa/src/lib/StockRow.tsx
import { memo } from 'react';
import type { StockState } from '../types.js';

interface Props {
  stock: StockState;
}

const StockRow = memo(function StockRow({ stock }: Props) {
  const dir            = stock.change >= 0 ? 'up' : 'down';
  const priceFormatted = stock.price.toFixed(2);
  const changeFormatted = (stock.change >= 0 ? '+' : '') +
                          (stock.change * 100).toFixed(2) + '%';
  const volumeFormatted = stock.volume.toLocaleString('en-US');

  return (
    <tr id={`row-${stock.symbol}`} className={`flash-${dir}`}>
      <td className="symbol">{stock.symbol}</td>
      <td className={`price ${dir}`}>{priceFormatted}</td>
      <td className={`change ${dir}`}>{changeFormatted}</td>
      <td className="volume">{volumeFormatted}</td>
    </tr>
  );
});

export default StockRow;
